### ISSUE TITLE
your indexed records for hikingsandiego. 2019. Plestiodon skiltonianus interaction->preyed on Falco sparverius. iNaturalist.org. Accessed at <https://www.inaturalist.org/observations/21276961> on 31 Dec 2022.

### ISSUE THREAD

**Issue by aeiche01** [globalbioticinteractions/inaturalist#5]
Hi!

Thanks for helping to make existing biotic interaction data easier to find and access!

I was just looking at your GloBI indexed record at https://www.globalbioticinteractions.org/?interactionType=eatenBy&sourceTaxon=Falco%20sparverius&targetTaxon=Plestiodon%20skiltonianus and I noticed that the record is reversed. It says the kestrel is eaten by western skinks, but the source says the reverse is true (western skink is eaten by kestrel)

**Comment by jhpoelen** [comment]
@aeiche01 thanks for sharing this suspicious record of a lizard eating a kestrel. That is kind of weird isn't it? 

The originating records at https://www.inaturalist.org/observations/21276961 shows a bird eating a lizard, rather than the other way around.

From the screenshot of the iNaturalist observation page, it appears that the author of making the interaction claim might have been confused about how the observations field "Preyed on" is interpreted. 

![Screenshot from 2023-01-09 13-58-00](https://user-images.githubusercontent.com/1084872/211397033-fb9f8e0d-1822-4951-8d52-20dc74d5af9a.png)

**Comment by jhpoelen** [comment]
Hi @aeiche01 - I attempted to update the observation field with a more reasonable claim. 

But, for some reason, I could not removed the original suspicious observation field after successfully adding a new onle.

@KatjaSchulz can you help?

https://www.inaturalist.org/observations/21276961#activity_comment_8d36eccd-df0b-4090-a0e6-7bd7e958e075

![image](https://user-images.githubusercontent.com/1084872/211399589-a77db8c3-f9a7-47d4-9088-54a264d13553.png)


![image](https://user-images.githubusercontent.com/1084872/211399812-8933883f-6363-454c-94b4-19d18f5e5b0c.png)

**Comment by KatjaSchulz** [comment]
Unfortunately I can't remove the erroneous data record. That can only be done by the person who added it.

**Comment by jhpoelen** [comment]
i've added a refutation records via https://github.com/globalbioticinteractions/refuted-interaction-data/commit/6925208aee8423db97f1f4f781b2cd0035e938e6 , so your refutation claim is recorded. 

I'll keep this issue open for a while to give the iNaturalist user https://www.inaturalist.org/people/hikingsandiego some time to respond.

**Comment by Optilete** [comment]
:-)

**Comment by jhpoelen** [comment]
https://www.inaturalist.org/people/hikingsandiego was kind enough to delete the suspicious observation records. 

Please allow some time for the changes to propagate, and hoping to close this issue after the update has made it to the GloBI index.

Thanks everyone!

![image](https://user-images.githubusercontent.com/1084872/212139768-0b02dc78-0dd4-443f-8d35-4786b1191c63.png)

**Comment by jhpoelen** [comment]
After GloBI index was rebuilt, I was able to see the refutation record appear at

https://www.globalbioticinteractions.org/?interactionType=eatenBy&sourceTaxon=Falco%20sparverius&targetTaxon=Plestiodon%20skiltonianus

![image](https://user-images.githubusercontent.com/1084872/218123964-16721c08-1119-4e5c-bd12-2766139cf760.png)


Along with the (updated, "corrected") interaction claim on https://www.inaturalist.org/observations/21276961

via 

https://www.globalbioticinteractions.org/?accordingTo=https%3A%2F%2Fwww.inaturalist.org%2Fobservations%2F21276961

![image](https://user-images.githubusercontent.com/1084872/218124246-65916ec0-80fe-4ecc-b9df-a0fbce5b93f9.png)

**Comment by jhpoelen** [comment]
@aeiche01 @Optilete @KatjaSchulz thanks for helping to make this happen. Please do share if you see other suspicious interaction claims.
